sudo: required
services: 
  - docker

before_install:
  - docker build -t rodrigosepulveda/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rodrigosepulveda/react-test npm test

after_success:
  - docker build -t rodrigosepulveda/multi-client ./client
  - docker build -t rodrigosepulveda/multi-nginx ./nginx
  - docker build -t rodrigosepulveda/multi-server ./server
  - docker build -t rodrigosepulveda/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rodrigosepulveda/multi-client
  - docker push rodrigosepulveda/multi-nginx
  - docker push rodrigosepulveda/multi-server
  - docker push rodrigosepulveda/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-228917064044'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY